[PHP]
extension_dir = "ext"
extension=curl
extension=openssl
extension=mbstring
extension=pdo_sqlite
extension=sqlite3

; Set max execution time
max_execution_time = 300
max_input_time = 60
memory_limit = 128M

; Error handling
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
html_errors = On
